=== peci1/Origamist/src/cz/cuni/mff/peckam/java/origamist/diagram.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
	xmlns:m="http://www.mff.cuni.cz/~peckam/java/origamist/diagram/"
	xmlns:c="http://www.mff.cuni.cz/~peckam/java/origamist/common/"
	xmlns:jxb="http://java.sun.com/xml/ns/jaxb"	
	jxb:version="2.0" 
	targetNamespace="http://www.mff.cuni.cz/~peckam/java/origamist/diagram/">

	<import namespace="http://www.mff.cuni.cz/~peckam/java/origamist/common/" schemaLocation="common.xsd"/>

	<annotation> 
		<appinfo>			
			<jxb:schemaBindings>
				<jxb:package name="cz.cuni.mff.peckam.java.origamist.model.jaxb"/>
			</jxb:schemaBindings>
		</appinfo>
	</annotation> 

	<element name="origami" type="m:Origami">
	</element>

	<complexType name="Origami">
		<annotation>
    		<appinfo>
    			<jxb:class implClass="cz.cuni.mff.peckam.java.origamist.model.Origami"/>
    		</appinfo>
    	</annotation> 
		<sequence>
			<element name="author" type="c:Author" />
			<element name="name" type="c:LangString"
				maxOccurs="unbounded" minOccurs="1">
				<annotation>
					<appinfo>
						<jxb:property 
							collectionType="cz.cuni.mff.peckam.java.origamist.utils.ChangeNotifyingList"/>
					</appinfo>
				</annotation>
			</element>
			<element name="year" type="gYear" />
			<element name="shortdesc" type="c:LangString"
				maxOccurs="unbounded" minOccurs="1">
				<annotation>
					<appinfo>
						<jxb:property 
							collectionType="cz.cuni.mff.peckam.java.origamist.utils.ChangeNotifyingList"/>
					</appinfo>
				</annotation>
			</element>
			<element name="description" type="c:LangString"
				minOccurs="1" maxOccurs="unbounded">
				<annotation>
					<appinfo>
						<jxb:property 
							collectionType="cz.cuni.mff.peckam.java.origamist.utils.ChangeNotifyingList"/>
					</appinfo>
				</annotation>
			</element>
			<element name="license" type="c:License" />
			<element name="original" type="anyURI" maxOccurs="1"
				minOccurs="0" />
			<element name="thumbnail" type="c:Image" />

			<element name="paper" type="m:DiagramPaper" />
			<element name="model" type="m:Model" />
		</sequence>
		<attribute name="version" type="positiveInteger" use="required"></attribute>
	</complexType>
    
    <complexType name="Paper" abstract="true">
    	<annotation>
    		<appinfo>
    			<jxb:class implClass="cz.cuni.mff.peckam.java.origamist.model.Paper"/>
    		</appinfo>
    	</annotation> 
    	<sequence>
    		<element name="size" type="m:UnitDimension"/>
    	</sequence>
    </complexType>
    
    <complexType name="DiagramPaper">
    	<annotation>
    		<appinfo>
    			<jxb:class implClass="cz.cuni.mff.peckam.java.origamist.model.DiagramPaper"/>
    		</appinfo>
    	</annotation>
    	<complexContent>
    		<extension base="m:Paper">
    			<sequence>
    				<element name="color" type="m:DiagramColors"/>
    				<element name="cols" type="positiveInteger"/>
    				<element name="rows" type="positiveInteger"/>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType>
    
    <complexType name="Model">
    	<sequence>
    		<element name="paper" type="m:ModelPaper"/>
    		<element name="steps" type="m:Steps">
    			<unique name="id">
    				<selector xpath="step"/>
    				<field xpath="@id"/>
    			</unique>
    		</element>
    	</sequence>
    </complexType>

    <complexType name="UnitDimension">
    	<annotation>
    		<appinfo>
    			<jxb:class implClass="cz.cuni.mff.peckam.java.origamist.model.UnitDimension"/>
    		</appinfo>
    	</annotation>
    	<complexContent>
    		<extension base="m:Dimension">
    			<sequence>
    				<element name="unit" type="m:Unit"/>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="Colors" abstract="true"/>
    
    <complexType name="Dimension">
    	<annotation>
    		<appinfo>
    			<jxb:class implClass="cz.cuni.mff.peckam.java.origamist.model.DoubleDimension"/>
    		</appinfo>
    	</annotation> 
    	<sequence>
    		<element name="width" type="double"/>
    		<element name="height" type="double"/>
    	</sequence>
    </complexType>

    <simpleType name="Unit">
    	<restriction base="string">
    		<enumeration value="mm"/>
    		<enumeration value="cm"/>
    		<enumeration value="m"/>
    		<enumeration value="km"/>
    		<enumeration value="inch"/>
    		<enumeration value="foot"/>
    		<enumeration value="mile"/>
    		<enumeration value="rel"/>
    	</restriction>
    </simpleType>

    <simpleType name="Color">
    	<annotation>
    		<appinfo>
    			<jxb:javaType name="java.awt.Color"
					parseMethod="cz.cuni.mff.peckam.java.origamist.utils.ColorConverter.parse"
					printMethod="cz.cuni.mff.peckam.java.origamist.utils.ColorConverter.print"/>
    		</appinfo>
    	</annotation>
    	<restriction base="string">
    		<pattern value="#[A-Fa-f0-9]{6}"/>
    	</restriction>
    </simpleType>

    <complexType name="DiagramColors">
    	<sequence>
    		<element name="background" type="m:Color"/>
    	</sequence>
    </complexType>

    <complexType name="ModelPaper">
    	<annotation>
    		<appinfo>
    			<jxb:class implClass="cz.cuni.mff.peckam.java.origamist.model.ModelPaper"/>
    		</appinfo>
    	</annotation>
    	<complexContent>
    		<extension base="m:Paper">
    			<sequence>
    				<element name="colors" type="m:ModelColors"/>
    				<element name="weight" type="double"/>
    				<element name="note" type="c:LangString" 
    					maxOccurs="unbounded" minOccurs="1">
    					<annotation>
							<appinfo>
								<jxb:property 
									collectionType="cz.cuni.mff.peckam.java.origamist.utils.ChangeNotifyingList"/>
							</appinfo>
						</annotation>
					</element>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="Steps">
    	<sequence>
    		<element name="step" type="m:Step" maxOccurs="unbounded" minOccurs="1"/>
    	</sequence>
    </complexType>
    
    <complexType name="ModelColors">
    	<sequence>
    		<element name="background" type="m:Color"/>
    		<element name="foreground" type="m:Color"/>
    	</sequence>
    </complexType>

    <complexType name="Step">
    	<annotation>
    		<appinfo>
    			<jxb:class implClass="cz.cuni.mff.peckam.java.origamist.model.Step"/>
    		</appinfo>
    	</annotation>
    	<sequence>
    		<element name="description" type="c:LangString"
    			maxOccurs="unbounded" minOccurs="1">
    			<annotation>
					<appinfo>
						<jxb:property 
							collectionType="cz.cuni.mff.peckam.java.origamist.utils.ChangeNotifyingList"/>
					</appinfo>
				</annotation>
    		</element>
    		<element name="colspan" type="positiveInteger"
    			default="1" maxOccurs="1" minOccurs="0" />
    		<element name="rowspan" type="positiveInteger"
    			default="1" maxOccurs="1" minOccurs="0" />
    		<element name="zoom" type="m:Percent" maxOccurs="1" 
    			minOccurs="0" default="100" />
    		<choice>
    			<element name="image" type="c:BinaryImage"/>
    			<element name="operation" type="m:Operation" maxOccurs="unbounded" minOccurs="0"/>
    		</choice>
    	</sequence>
    	<attribute name="id" type="int" use="required"/>
    </complexType>

    <simpleType name="Percent">
    	<restriction base="double">
    		<minInclusive value="1.0"/>
    	</restriction>
    </simpleType>

    <complexType name="Operation">
    	<annotation>
    		<appinfo>
    			<jxb:class
    				implClass="cz.cuni.mff.peckam.java.origamist.model.Operation" />
    		</appinfo>
    	</annotation>
    	<sequence>
    		<element name="angle" type="double" minOccurs="0" />    		
    		<element name="startPoint" type="m:Point2D" minOccurs="0" />
    		<element name="endPoint" type="m:Point2D" minOccurs="0" />
    		<element name="layer" type="int" maxOccurs="unbounded" minOccurs="0" />
    	</sequence>
    	<attribute name="type" type="m:Operations" use="required" />
    </complexType>

    <simpleType name="Operations"> 
    	<restriction base="string">
    		<enumeration value="VALLEY_FOLD"/>
            <enumeration value="MOUNTAIN_FOLD"/>
            <enumeration value="MOUNTAIN_VALLEY_FOLD_UNFOLD"/>
            <enumeration value="VALLEY_MOUNTAIN_FOLD_UNFOLD"/>
            <enumeration value="THUNDERBOLT_FOLD"/>
            <enumeration value="TURN_OVER"/>
            <enumeration value="ROTATE"/>
            <enumeration value="PULL"/>
            <enumeration value="INSIDE_CRIMP_FOLD"/>
            <enumeration value="OUTSIDE_CRIMP_FOLD"/>
            <enumeration value="OPEN"/>
            <enumeration value="INSIDE_REVERSE_FOLD"/>
            <enumeration value="OUTSIDE_REVERSE_FOLD"/>
            <enumeration value="REPEAT_ACTION"/>
            <enumeration value="RABBIT_FOLD"/>
            <enumeration value="SQUASH_FOLD"/>
    	</restriction>
    </simpleType>
    
    <simpleType name="positiveInteger">
    	<annotation>
    		<appinfo>
    			<jxb:javaType name="Integer" 
					parseMethod="javax.xml.bind.DatatypeConverter.parseInt"
					printMethod="javax.xml.bind.DatatypeConverter.printInt"/>
    		</appinfo>
    	</annotation>
    	<restriction base="integer">
    		<minExclusive value="0"/>    		
    	</restriction>
    </simpleType>
    
    <complexType name="Point2D">
    	<sequence>
    		<element name="x" type="double"></element>
    		<element name="y" type="double"></element>
    	</sequence>
    </complexType>
</schema>

=== peci1/Origamist/src/cz/cuni/mff/peckam/java/origamist/diagram.xml
<?xml version="1.0" encoding="UTF-8"?>
<m:origami version="1" xmlns:m="http://www.mff.cuni.cz/~peckam/java/origamist/diagram/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mff.cuni.cz/~peckam/java/origamist/diagram/diagram.xsd">
  <author>
    <name>Kawasaki</name>
    <homepage>http://www.mff.cuni.cz</homepage>
  </author>
  <name>Kawasaki rose</name>
  <year>2010</year>
  <shortdesc>A very nice, but hard rose model.</shortdesc>
  <shortdesc lang="cs-CZ">Opravdu překrásná růže, ale složitá.</shortdesc>
  <description>A very nice, but hard rose model. This has nothing to do with the czech film...</description>
  <description lang="cs-CZ">Opravdu překrásná růže, ale složitá. Nemá nic společného s českým filmem...</description>
  <license>
    <name>BSD</name>
    <content>You can do whatever you want except hiding or changing the authorship information.</content>
    <permission>export</permission>
    <permission>edit</permission>
    <permission>distribute</permission>
    
  </license>
  <thumbnail>
    <image type="image/jpeg">0</image>
  </thumbnail>
  <paper>
    <size>
      <width>200</width>
      <height>297</height>
      <unit>mm</unit>
    </size>
    <color>
      <background>#ffff22</background>
    </color>
    <cols>3</cols>
    <rows>3</rows>
  </paper>
  <model>
    <paper>
      <size>
        <width>20</width>
        <height>30</height>
        <unit>cm</unit>
      </size>
      <colors>
        <background>#5555ff</background>
        <foreground>#ff8888</foreground>
      </colors>
      <weight>80</weight>
      <note>A common sheet of red A4 paper.</note>
      <note lang="cs-CZ">Obyčejný červený list papíru A4.</note>
    </paper>
    <steps>
      <step id="1">
        <description>Begin with a square.</description>
        <description lang="cs-CZ">Začneme se čtvercem.</description>      
      </step>
      <step id="2">
      	<description>Rotate it 45° clockwise.</description>
      	<description lang="cs-CZ">Otočte ho o 45° doprava.
      		Tohle je šíleně dlouhý dvouřádkový popisek. Určitě se na jeden řádek nemůže vejít. Lorem ipsum
      		Lorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsum</description>
      	<operation type="ROTATE">
      		<angle>0.7853</angle>
      	</operation>
      </step>
      <step id="3">
      	<description>Make a diagonal valley fold.</description>
      	<description lang="cs-CZ">Udělejte na úhlopříčce údolní přehyb.</description>
      	<operation type="VALLEY_FOLD">
      		<startPoint><x>0</x><y>0</y></startPoint>
      		<endPoint><x>0.6666666</x><y>1</y></endPoint>
      		<layer>1</layer>
      	</operation>
      </step>
    </steps>
  </model>
</m:origami>

=== peci1/Origamist/diagrams/diagram.xml
<?xml version="1.0" encoding="UTF-8"?>
<m:origami version="1" xmlns:m="http://www.mff.cuni.cz/~peckam/java/origamist/diagram/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mff.cuni.cz/~peckam/java/origamist/diagram/diagram.xsd">
  <author>
    <name>Kawasaki</name>
    <homepage>http://www.mff.cuni.cz</homepage>
  </author>
  <name>Kawasaki rose</name>
  <year>2010</year>
  <shortdesc>A very nice, but hard rose model.</shortdesc>
  <shortdesc lang="cs-CZ">Opravdu překrásná růže, ale složitá.</shortdesc>
  <description>A very nice, but hard rose model. This has nothing to do with the czech film...</description>
  <description lang="cs-CZ">Opravdu překrásná růže, ale složitá. Nemá nic společného s českým filmem...</description>
  <license>
    <name>BSD</name>
    <content>You can do whatever you want except hiding or changing the authorship information.</content>
    <permission>export</permission>
    <permission>edit</permission>
    <permission>distribute</permission>    
  </license>
  <thumbnail>
    <image type="image/jpeg">R0lGODlhlgA3APf9AABpCwB0CwF8DSt8Njt1REl8Tkl9UZgVKakII7UKJroLJ7oXLLMqOcMNKswNK9MOLs0SLNMULdsTLtYbLtobL8kbMt0VMN4cMuIbMc8sOtkoOuYiNOonNewqNeszO/IzOPU7O7hwLdFfBdhpA9t1C+F6A/dBPaw8SNE4Rek5Q/E+QpVESZBNUbFRU65qVqhdYJdwcKRoaLByctFLUuxFR/VJR+pSVPhbVNBhXvhjWstbYNhpbMZ8efZsZOp0dPF6dQSBDgCIEAGUEQObEwOlGwemGAuxHRmOKgqqJA2yIxe5KCrENz2eTkuCU1WlY1uzaTfHRGPLceiJBeuUCvKTAvObB+ecGfylBf+uB/WjDP2tC/+xDO+oHPitFP63GNKMLNuVLfu5JuquM//BKf/FNLaJUJmIcrSMc6WUecaPTum4T8+OcveEes+scv7KRfjKVvjRbjBDmzlOpjJJrTNNtDJOvDlTuEhXkFVlnGp1mEVdtlhqp01lu1VqsVVrt2d2p2x4pGh7tzVTwzpYxDZXyDdZyzlbzTte0T9gzj1i1T9m2kFdwklmyFFqw1x2x0Fl1EVq1Upt1EBm20Jq3Uxy2lh52GF8zENt4UVx40p15Ep45UZ06E176VF+5eV8gnuDl3eEqW+BvHeHt3zWhXiNzmiE1leF6l6Q72SK5mqU7Hma6Xuh7ZeMi4eMl5eUlpubnLKSkLenkoONqY6WqZebp4mVtZ2hqZ2ktqOjpKalqKqqq7Krqqers6+zsLOzs7y5tLy8vNSame+OicilkO+hn82zr+imovi2rOq4tqHbp9fBkvfXiO3RkejWq/LPsPnmtYmYxoOa2pOm2Kmww7i8xKy42Iek6JWt5puz6pCw8aa66aW+8bzC0arA77zJ6avC8rXJ9MPDw8nIyMvLzNTKyMrP0NPT09PW3Nzc3OrKx/TJw+7VzfbZ1s3l0Pfqz8vV7NPd9N3o5N3k9OTk5Ovm5uzs7Pbs6vX46ubr9eTr+u3y/PPz8/n29v///wAAAAAAACH5BAAAAAAALAAAAACWADcAAAj+APsJHEiwoMGDCBMqXMiwocOHECNKnEixosWF/O4lG8UxypMn7fhdjKgP3jds1lSpsnZNmzd5+0bKnKlQI5QlN5cYKYIGXUyaCfWBU8UpE6ZJSC8puoRJUydU1rrhEwm06sV77bglU6LEiJAjusxRtTowHzZTmyZVEjXrlq1ctmaBciRpEiVNlUxFezeWrF+H9+KF41oESJNf9PpaBXcqbaBZuXyFK3cOHTpz48LdCoRIkd1JikjF0/e3dMN9SpIMMRyu3l992UxhigTK1i9z8/bxo7p73zxztxglGl6oDql5ik0rH8iPMOufVuWtMjXJT6tc4xIr5FePmx9Cder+4MF1Lvny5UuUFDYQDjpQfdMvMWrVy6fDfej40MHjChjy8wAK1FwShTXRmlX8xLYJIp/ogo55BY31jh1/vOJfgBgOWGB7Vn3TWCJ74FKOew15Uw0w4cyD4YqpDSEAe64BJc8p1M13YET8zIOOdisC2Jx6AhhI4kjZNIbIHrk8ONFuEEHYI0NjDegie0NalA+NlxTyCTAx/iUSO8cI88MPwhCTjpMH8ePOMm6QMcYYZMCxjDv6oElQSeCAs82e22iDDTbZsCSPgC2+eONB9oTZQw9kIsPjQds0JskgrohVGj/H3ACCCTbQ8IEKoNogzKMJufPGm2q00YYYXnjxJhz+7tjJzzvWmMIJJ6bkakonm0iiyCPRKMlPEkZMyaFB9ghTQw02dArCsjYYU2U/qqCVCB+5qOgXP+r0YAIOsOjiyy+7nJHCuSnQgAxpCN0DxxhhDNPLLygCEwurrnrBjG4IvXPKJaVAA00lk1yiSSaTBKJwLtTY1xwSQhhKIj/O3PDBGrvs4ksvPHgAago71KNYPrZucsgevnRpVaYg8KALMOagM8885xQzAwfnbhDMkLu9K0YsuoSDTj1EzzOOGFu0usUwKguYDSed8OILMNRQU0tdSAWSC4roTCVQEkS4KGRBmX4QrtAznzNMCh5wsAEPTb9jiiaXGPIHl34dk8P+t7SkGGU95KSAgdsWFNO0u2R4gUZYTe9jDhdJa3GFMuwOFNsls/iCW9HQKCKJJImEco7IzCWBxBABFHCsQM7sLQMu5PDI3RodYDBBBYYT9M3ckxzyx+o08cNODzV4wMovrim2TzAYbICBBCiY494zboLxyohpKqPFFpJbYalAjG0SiIh/l1KXIodM0zTYqFM5kD3EG3/oQOlQAIECCcSgpEBP0+37/DPhBxty8IEW4GJ/BqnHDDCAAQs8QAb0GMg92sSFMvRCWwbhxz7EoAXJTaEN/9FHKkxxCUD4IoIE4Uc5JKGUQwTie/0YFhGEEAD3CSRTJphBkpJDjAksAAH+B4BBOcbyNIQlwg8AlEm3arCBGCAvIfwwBgMtEIEFiOMny3CTFdBwRSjCQQtYuAIVvtBFcNhKEYAAnoA6cQnQDQJvA9kJDWEkoB5Y7AUpi9IxbFBFFsDAQgjERiYycYlrwTF4wriBCSYAA3HcQyH02MAFHNgAWKhogombAhqGqBB3gFGMUmBaPxQkCUCMwzzX+NwhCGELDPIDCWGr4Y3WcYMafMAFcOQHMVSwARS8bhcwyw1BtGGUQjKCF00biT1q+QFGnnI7NpikAxTwgvJQbwxe0GR5tiOGMFKhBGVARz9SURRJBKKLBvGGUgxhB1pgsB+wnOOxMmXLFoTDHuz++EHtwKUxcQwtOd7YxCbWOYt3yoQdy2pmDDipEE9IUwErEAc/sjiGLmgyJAt5gzdLkIYhkjMtjUhiP+DRxkLYwRbiFBAs23csZYGgAy2IhQ08kII1iAsY48gNhORxiZ6C7oV2iog6QNWBCbgAewpBhjQTsILWvMsLXJjCGWCYpmWEUQolCMEVVSFQ0PDCoALhqSIEgYdsMWelsvyJSzuQgV2EgxzcAIY/SbcdNraQEdRIJkL4oQ9tXOOv18CGNK4Rjb3swxkq+EAHKGDPadGvgQ5AwAq4tAxsamEKZeDGIxXSjKuOIAQj0kZPFaEI0SUHHpMwRB3y8ESVzjCtAhH+Bgg+wIEJxOIc84jHPOjKEGkspYW1+M9C8HEN0CgCEpTIVSUgUQhHjKMe6fhACjhgAQYcEiHsmGQDEMCC1lTWC5f9Qjg2u9dnYKEKUhhBGYaID4IpJRLqM4g2JEFWXMDwlRCDbT+M8QHFUkAG24zIO37rq0igMyjgEOwtZsFgSkSCue1sDTs6wAEOUKACsQBrQdjhQAUgAAbc2Ic7WqWFLExhF3olyDOuUIUSiAANYuFHNRSRCKQ44hyV60c9MmGIPfRHZa98rQ3V0QEKU2AGSIXIPizxOVUeR1a/IUc5zMENSCDCEIKQwyvOEUMbbMB5EZABAg+yDgcm4ACtEMv+PThY4iqcYcwGYYYYP5skgdhDGoYwxCEUUYkQx1BuiQjEK36hoijFU5YxskcKKLyBCcAixQspx5599av4LmQfmNagPCCRiOLIQRfakiIDKZCBeybVAttdgVn7wYwsuDoLZHRsP+BwBReb4ZD1mAYfBmGIRGACFasYoSRCgQv/KOaVQ6Ch6n7CDx9o4MsYyMAzSUKKQ+yZtJFIckPwYWVPg9rOKKCAuCtgyYY+QAEHYMWN6mEFV1fhg/FQSBi+GYJXSI859SjHLUDxB1GUIleQYISFUGiQ0wkBADbsRzouwHAMUEAHwn0IP+QRCWuTVhGRCPC2IaEIb2uLH8WIAAT+IhCBUkOIHxrYLgtQyptmUGEKU6iCFa5onhXbOq8G2Qc90CEObpQiE5RQRCNyEQ/z4FeeXeIHDyYwAQowcAcRd4gKF1GIQyTCM5Tw87YjkYhB0EEOX5UgDyBA9gjoAM4C8UGqXyEOle1jGFKQQszFgPZ7eIEKJDDDLtAuIEyXAhNKWcQtNCyQeAZpdfygBwpGLgEJXGAGZ8qgoxCyD2oMghBVJ+0kpMHbhHC7EIKYwxxWLZB6yKABDXCA2dFRJ+Z44twrcEUS69GGuEuhCmJYh0io4o555z0X916INY4CmklUg18RglgQAjCAXpA3huRgAAQcAIHGY2AHxkgHPdj+gQxPoMBwEOqOHwSB+T1DohTVgLRA8HEIQdAhDnEIO3PoAQsGKMABDtCAMNLBDnYQAwUPwAAwgAvhQCoCgg/F8AUlcHtXoAbL0AyVdQVSkAav0AvBtxDvQAlIQVqQwHkGwQTLBwAAEABAcARNkAy8QQ4toAAK0ADT13iN9wAOgDvZ4SSOAwp0UAd2gHmeUQnS8BKtJxAlcQ2REHrwdwfyh2/hAAMnsACo9wAS8AAPcAIyEBnj4DVpUg/mEAtl8AVSQAVVAIZg0Aax0AtCE1T5AA/vUAl6dnVKQQq8FQ9P0AQEUId26ARtNxD4AQsngAB+mAAJwIIM8AJb4xNokiP+1AAIdlAH5FcIvfYIkFAJlVAKlUAJhgB6doAHeZAHroAdeoUfxSADL9ACpBgDMuBWOSVrAjIP4dAGafCKabAGsfALQtN5BZEP35AKQddxjKAHglB1VzcJTzYQWhgOKBIO3BAO/oR8McSKsPACKxCNLBADrrAL4hB1ClEP6MANs/AHeqAHdmAHgjCOg6AHfOAHoCALtKAL4jIZu2WDOmIO5TAO4xAz9cCMDHEP9bBzloEO8UAP+FgQ8mANnPArpFALt8ALvKALs6AHwIg+0OBK+3CPE4lptigQE3kZ4iAO9Cgz6peFPHcLsvAHf7AHe0CSgKCOvkAN9bhbuhFUArL+GzJpEVGiELszCY8ACq+wNfUoM+gQDoFACHp2CIWAcxTRG5imilCyjzpyGTEjM7slMjD5JLpDHQxCgEPDL7uHDqIglIZACKCQUlS5VwIylhUBD6iQCYeQB7bwXEY3D6SQZ3awBwe2IlNplhGRD9XSca1wXRk0D4wAenrgl3hZmBYBDp0QdO0kllAUDSa1B61lmJJZEdcAeIdgCCzHENdQCHSQB0Y5maAZEdhgXIYgC4yZEI5JB60wbaHZmg3xDhVndYwQDnaiD0WYBzvkmrrZW9a2ZzeGJtEgCH3wCmq0m8ZJEPVgCYVQdYdACdWADzEUnSIhD6UwCH1AC8Z2nNptGSHoEAiMSAjWNgml0BLaoA3WUAmXKQpbg43bqZ05cgt7EI6NmGdESQh8oJ69kFN32Z6TyR3lwAuyAAh5YJJ/AAigsI6+IA7xoJT8uZsZWQ7GCAwSGg4x844NeqFpokFEk2n7iaEe+qEgGpoBAQA7</image>
  </thumbnail>
  <paper>
    <size>
      <width>200</width>
      <height>297</height>
      <unit>mm</unit>
    </size>
    <color>
      <background>#ffff22</background>
    </color>
    <cols>3</cols>
    <rows>3</rows>
  </paper>
  <model>
    <paper>
      <size>
        <width>20</width>
        <height>30</height>
        <unit>cm</unit>
      </size>
      <colors>
        <background>#5555ff</background>
        <foreground>#ff8888</foreground>
      </colors>
      <weight>80</weight>
      <note>A common sheet of red A4 paper.</note>
      <note lang="cs-CZ">Obyčejný červený list papíru A4.</note>
    </paper>
    <steps>
      <step id="1">
        <description>Begin with a rectangle.</description>
        <description lang="cs-CZ">Začneme s obdélníkem.</description>      
      </step>
      <step id="2">
      	<description>Rotate it 45° clockwise.</description>
      	<description lang="cs-CZ">Otočte ho o 45° doprava.</description>
      	<operation type="ROTATE">
      		<angle>0.7853</angle>
      	</operation>
      </step>
      <step id="3">
      	<description>Make a valley fold parallel to the bottom of the paper.</description>
      	<description lang="cs-CZ">Rovnoběžně se spodní hranou papíru udělejte údolní přehyb.</description>
      	<operation type="VALLEY_FOLD">
      		<startPoint><x>0</x><y>0.2</y></startPoint>
      		<endPoint><x>0.666666666</x><y>0.2</y></endPoint>
      		<layer>1</layer>
      		<angle>1</angle>
      	</operation>
      </step>
      <step id="4">
      	<description>Make a mountain fold parallel to the top of the paper.</description>
      	<description lang="cs-CZ">Rovnoběžně s horní hranou papíru udělejte horní přehyb.</description>
      	<operation type="MOUNTAIN_FOLD">
      		<startPoint><x>0</x><y>0.8</y></startPoint>
      		<endPoint><x>0.666666666</x><y>0.8</y></endPoint>
      		<layer>1</layer>
      		<angle>2</angle>
      	</operation>
      </step>
      <step id="5">
      	<description>Rotate it 45° backwards.</description>
      	<description lang="cs-CZ">Otočte ho zase o 45° zpět.</description>
      	<operation type="ROTATE">
      		<angle>-0.7853</angle>
      	</operation>
      </step>
      <step id="6">
      	<description>Turn the paper over.</description>
      	<description lang="cs-CZ">Otočte papír vzhůru nohama.</description>
      	<operation type="TURN_OVER"/>
      </step>
    </steps>
  </model>
</m:origami>
